# Basic Configuration
baseURL = "/"
languageCode = "en-us"
title = "Eteo"
theme = "hugo-saasify-theme"

# Pagination Configuration
[pagination]
  pagerSize = 12  # Number of posts per page
  path = "page"  # URL format like /blog/page/2/

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = false     # Disable Git info for now

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS
  
# Disable PostCSS processing
[params.assets]
  disablePostCSS = true
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2



# Theme Parameters
[params]
  description = "Your site description"
  author = "Your Name"
  logo = "/images/logo.svg"      # Path to your logo
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  googleAnalytics = "G-XXXXXXXXXX"  # Only enabled in production

  # Google Tag Manager ID (e.g., "GTM-XXXXXXX")
  # Only enabled in production
  googleTagManager = "GTM-XXXXXXX"

  # Header Configuration
  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Header Logo
    [params.header.logo]
      src = "/images/logo.svg"
    
    # Header Buttons (optional)
    [params.header.buttons]
      [params.header.buttons.signIn]
        text = "Sign in"
        url = "/signin"
      [params.header.buttons.getStarted]
        text = "Get Started"
        url = "/get-started"

  # Global CTA Configuration (optional)
  [params.cta]
    enable = true
    title = "Ready to Get Started?"
    description = "Join companies using our platform"
    [params.cta.primary_button]
      text = "Get Started Free"
      url = "/get-started"
    [params.cta.secondary_button]
      text = "Book Demo"
      url = "/demo"

  # Footer Configuration
  [params.footer]
    column_1_title = "Info"
    column_2_title = "Better Integration"
    column_3_title = "Contact"

  # Social Media Links (optional)
  [params.social]
    linkedin = "https://linkedin.com/in/yourusername"
    twitter = "https://twitter.com/yourusername"
    github = "https://github.com/yourusername"

# Navigation Menu
[menu]
  [[menu.main]]
    name = "Free Theory"
    url = "/theory"
    weight = 1
  [[menu.main]]
    name = "Contact Us"
    url = "/contact"
    weight = 2
  [[menu.main]]
    name = "Theory tests"
    url = "/tests"
    weight = 3
  [[menu.main]]
    name = "Theory books"
    url = "/books"
    weight = 4

# Footer Menus
  # Footer Column 1 - Info
  [[menu.footer_column_1]]
    name = "Free Theory"
    url = "/theory"
    weight = 1
  [[menu.footer_column_1]]
    name = "Contact Us"
    url = "/contact"
    weight = 2
  [[menu.footer_column_1]]
    name = "Theory tests"
    url = "/tests"
    weight = 3
  [[menu.footer_column_1]]
    name = "Theory books"
    url = "/books"
    weight = 4
  [[menu.footer_column_1]]
    name = "About us"
    url = "/about"
    weight = 5

  # Footer Column 2 - Better Integration
  [[menu.footer_column_2]]
    name = "South Kullerød 8"
    url = "#"
    weight = 1
  [[menu.footer_column_2]]
    name = "3241 Sandefjord"
    url = "#"
    weight = 2
  [[menu.footer_column_2]]
    name = "post@eteo.no"
    url = "mailto:post@eteo.no"
    weight = 3
  [[menu.footer_column_2]]
    name = "org. no.: 935733944"
    url = "#"
    weight = 4

  # Footer Column 3 - Contact
  [[menu.footer_column_3]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 1